Merging 4.1.99-a1 into the debian branch.

diff --git a/doc/Makefile.am b/doc/Makefile.am
--- a/doc/Makefile.am
+++ b/doc/Makefile.am
@@ -1,4 +1,4 @@
-## $Id: Makefile.am,v 1.1.2.2 2001/06/30 03:19:58 sharkey Exp $
+## $Id: Makefile.am,v 1.1.2.3 2001/07/10 20:22:46 sharkey Exp $
 ## Copyright (C) 2000 Roger Leigh
 ##
 ## This program is free software; you can redistribute it and/or modify
@@ -23,36 +23,47 @@ AUTOMAKE_OPTIONS = 1.4 gnu
 
 MAINT_CHARSET = latin1
 
+
+## Variables
+
 DOCS = \
  FAQ.html \
- README.dither \
- README.escp2 \
  README.maintaining \
- README.new-printer \
- README.weave \
  docbook.css \
  print-color.png \
  print-main.png \
  print-setup.png \
  print.html \
- print.sgml
+ print.sgml \
+ html-stamp
+
+
+## Data
 
 info_TEXINFOS = gimpprint.texi
 
-gimpprint_TEXINFOS = gpl.texi
+gimpprint_TEXINFOS = overview.texi copying.texi gpl.texi introduction.texi using.texi functions.texi programs.texi problems.texi appendices.texi dither.texi weave.texi escp2.texi new-printer.texi indices.texi integrating.texi
+
+
+## Rules
 
 all-local: html
 
 html: html-stamp
-html-stamp: gimpprint.texi version.texi gpl.texi
+
+## Note the rather weird way of setting the exit status; this is because
+## texi2html doesn't set the exit status.
+html-stamp: gimpprint.texi $(gimpprint_TEXINFOS)
+	stat=1; \
 	if test x$(TEXI2HTML_PROG) != x ; then \
 	  rm -rf manual-html ; \
 	  mkdir manual-html ; \
 	  cd manual-html ; \
 	    $(TEXI2HTML_PROG) -menu -split_node -number -expandinfo \
-	    -I ../$(srcdir) ../$(srcdir)/gimpprint.texi ; \
-	fi
-	
+	    -I ../$(srcdir) ../$(srcdir)/gimpprint.texi 2>&1 | grep . ; \
+	    stat=$$? ; stat=`expr 1 - $$stat` ; \
+	fi; \
+	exit $$stat
 	touch html-stamp
 
 dist-hook: html
@@ -69,6 +80,9 @@ dist-hook: html
 
 maintainer-clean-local:
 	rm -rf manual-html
+
+
+## Clean
 
 DISTCLEANFILES = html-stamp
 MAINTAINERCLEANFILES = Makefile.in
